import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";

// Load Inter font
const inter = Inter({
  subsets: ["latin"], // You can specify other subsets if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
